class SignUpLocators():
    text_signup_button_tagname = "Register"
    text_first_name_id = "customer.firstName"
    text_last_name_id = "customer.lastName"
    text_address_id   = "customer.address.street"
    text_city_id = "customer.address.city"
    text_state_id = "customer.address.state"
    text_zip_id = "customer.address.zipCode"
    text_phonenumber_id = "customer.phoneNumber"
    text_ssn_id = "customer.ssn"
    text_username_id = "customer.username"
    text_password_id = "customer.password"
    text_password_confirm_id = "repeatedPassword"
    text_register_button_xpath = "//input[@value = 'Register']"
